import { describe, expect, it } from "vitest";
import document from "@/lib/openapi.json";

type OpenApiDocument = {
  paths: Record<string, Record<string, unknown>>;
};

// QC verification (DRK-309): the statistics endpoints that back the /status view must be
// published under /api/statistics/ in the generated API specification. `lib/openapi.json` is
// regenerated by the pretest hook (`node scripts/generate-openapi.mjs`) from `app/api`, so these
// assertions verify the actual published document, not a hand-written fixture.
describe("statistics endpoints in the published OpenAPI document (DRK-309)", () => {
  const paths = (document as unknown as OpenApiDocument).paths;

  it("documents GET /api/statistics/traffic", () => {
    expect(paths["/api/statistics/traffic"]).toBeDefined();
    expect(paths["/api/statistics/traffic"].get).toBeDefined();
  });

  it("documents GET /api/statistics/storage", () => {
    expect(paths["/api/statistics/storage"]).toBeDefined();
    expect(paths["/api/statistics/storage"].get).toBeDefined();
  });

  it("documents GET /api/statistics/webhooks", () => {
    expect(paths["/api/statistics/webhooks"]).toBeDefined();
    expect(paths["/api/statistics/webhooks"].get).toBeDefined();
  });

  it("documents GET /api/statistics/webhooks/{id}/requests", () => {
    expect(paths["/api/statistics/webhooks/{id}/requests"]).toBeDefined();
    expect(paths["/api/statistics/webhooks/{id}/requests"].get).toBeDefined();
  });

  it("documents GET and DELETE /api/statistics/cleanup", () => {
    expect(paths["/api/statistics/cleanup"]).toBeDefined();
    expect(paths["/api/statistics/cleanup"].get).toBeDefined();
    expect(paths["/api/statistics/cleanup"].delete).toBeDefined();
  });
});
