name: Publish NuGet package

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/TestContainer.Webhook
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Calculate version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: false
          search_commit_body: false

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - run: dotnet restore

      - run: dotnet build --configuration Release --no-restore

      - run: dotnet pack --configuration Release --no-build -p:Version=${{ steps.version.outputs.version }} -o ./nupkg

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: baoduy2412
          
      - name: Push to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
